version: '3.8'

services:
  super-prediction-api:
    build: .
    container_name: super-prediction-model
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - prediction-network

  redis:
    image: redis:7-alpine
    container_name: prediction-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - prediction-network

  nginx:
    image: nginx:alpine
    container_name: prediction-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - super-prediction-api
    restart: unless-stopped
    networks:
      - prediction-network

volumes:
  redis_data:

networks:
  prediction-network:
    driver: bridge