[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "bash"]

[phases.install]
cmd = "python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt"

[phases.build]
cmd = "python3 test_python.py"

[start]
cmd = "bash start.sh"