# GSMT Ver 7.0 Enhanced - Railway Deployment Configuration
# Pure Python FastAPI backend deployment

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "python app.py"

[variables]
PORT = "8000"
PYTHONPATH = "/app"